export const projects = [
    {
        title: 'Anon',
        description: "A simple narrative game where you learn basic OSINT skills and track down your missing friend. School project for Software Project Management. My role included building Levels 1-2.",
        tags: ['Game Projects'],
        link: 'https://venushmallow.github.io/Anon/',
        id: 0,
    },
    {
        title: 'Housemates from Hell',
        description: "A very simple game made for GMTK Game Jam 2021 (theme: Joined Together) in under 48 hours using free assets from Kenney and OpenGameArt. For MacOS.",
        tags: ['Game Projects'],
        link: 'https://wallflower6.itch.io/housemates-from-hell',
        id: 1,
    },
    {
        title: 'Lame Space Collector',
        description: "Collect stars and gems in a spacecraft but keep an eye out for asteroids! Inspired by snake, a project to try some beginner's independent work in Unity.",
        tags: ['Game Projects'],
        link: 'https://wallflower6.github.io/LameSpaceCollector/',
        id: 2,
    },
    {
        title: 'Pong Clone',
        description: "Pong clone, drew on Noobtuts' tutorial. Added in some extras, like a trail effect, increasing speed, single-player mode, scoreboard, menu, audio.",
        tags: ['Game Projects'],
        link: 'https://wallflower6.github.io/PongClone/',
        id: 3,
    },
    {
        title: 'Toothless (CSS)',
        description: "Toothless from Dreamworks' How To Train Your Dragon, made with CSS. A simple project to celebrate the release of the third film, The Hidden World.",
        tags: ['Web'],
        link: 'https://codepen.io/wallflower6/full/MLmJLj',
        id: 4,
    },
    {
        title: 'Tribute Page',
        description: "A tribute page to Alan Turing, made as a freeCodeCamp project. The UI was inspired by the Bletchley Park bombe, but greyed out.",
        tags: ['Web'],
        link: 'https://wallflower6.github.io/tribute-page/',
        id: 5,
    },
    {
        title: 'House of Quotes',
        description: "A random quote machine, made as a freeCodeCamp project. Fetches from the Forismatic API.",
        tags: ['Web'],
        link: 'https://codepen.io/wallflower6/full/NvPdvN',
        id: 6,
    },
    {
        title: 'Wikipedia Viewer',
        description: "Search and view wikipedia articles, made as a freeCodeCamp project. Uses the Wikipedia API.",
        tags: ['Web'],
        link: 'https://codepen.io/wallflower6/full/WdbpWL',
        id: 7,
    },
    {
        title: 'Product Landing Page',
        description: "How To Train Your Dragon-themed product landing page, a freeCodeCamp project. Frontend only, with no backend functionality.",
        tags: ['Web'],
        link: 'https://codepen.io/wallflower6/full/omeBYx',
        id: 8,
    },
    {
        title: 'Whack-A-Char',
        description: "Based on Wes Bos's JS30 tutorial, modified with characters from my favourite films, includes a mallet and sound effects.",
        tags: ['Web'],
        link: 'https://wallflower6.github.io/whack-a-char/',
        id: 9,
    },
    {
        title: 'Blender: Doughnut',
        description: "Followed Blender Guru's doughnut tutorial, and here's my final render. It was my first attempt at 3D modelling, texturing and lighting.",
        tags: ['CG'],
        link: 'https://drive.google.com/file/d/1np4tHk0nE_ebUuQckdqy7Wz482BCKMK5/view?usp=sharing',
        id: 10,
    },
    {
        title: 'Blender: Sword Scene',
        description: "Followed CG Fast Track's tutorial series. I got to brush up on 3D modelling, learned to use HDRIs, imported assets, was introduced to composition.",
        tags: ['CG'],
        link: 'https://drive.google.com/file/d/1y6MLLDpA7E_KcbsmwT67G7lxyGq0-ecc/view?usp=sharing',
        id: 11,
    }
];